// 题目轻量索引（由 tools/generate-manifests.mjs 生成，请勿手改）

export const problems = [
  {"id":1,"title":"两数之和","slug":"two-sum","difficulty":"easy","tags":["数组","哈希表"]},
  {"id":2,"title":"两数相加","slug":"add-two-numbers","difficulty":"medium","tags":["链表","数学"]},
  {"id":3,"title":"无重复字符的最长子串","slug":"longest-substring-without-repeating-characters","difficulty":"medium","tags":["哈希表","字符串","滑动窗口"]},
  {"id":4,"title":"寻找两个正序数组的中位数","slug":"median-of-two-sorted-arrays","difficulty":"hard","tags":["数组","二分查找","分治"]},
  {"id":5,"title":"最长回文子串","slug":"longest-palindromic-substring","difficulty":"medium","tags":["双指针","字符串","动态规划"]},
  {"id":11,"title":"盛最多水的容器","slug":"container-with-most-water","difficulty":"medium","tags":["数组","双指针"]},
  {"id":15,"title":"三数之和","slug":"3sum","difficulty":"medium","tags":["数组","双指针","排序"]},
  {"id":17,"title":"电话号码的字母组合","slug":"letter-combinations-of-a-phone-number","difficulty":"medium","tags":["哈希表","字符串","回溯"]},
  {"id":19,"title":"删除链表的倒数第 N 个结点","slug":"remove-nth-node-from-end-of-list","difficulty":"medium","tags":["链表","双指针"]},
  {"id":20,"title":"有效的括号","slug":"valid-parentheses","difficulty":"easy","tags":["栈","字符串"]},
  {"id":21,"title":"合并两个有序链表","slug":"merge-two-sorted-lists","difficulty":"easy","tags":["链表","递归"]},
  {"id":22,"title":"括号生成","slug":"generate-parentheses","difficulty":"medium","tags":["字符串","动态规划","回溯"]},
  {"id":23,"title":"合并 K 个升序链表","slug":"merge-k-sorted-lists","difficulty":"hard","tags":["链表","分治","堆（优先队列）","归并排序"]},
  {"id":24,"title":"两两交换链表中的节点","slug":"swap-nodes-in-pairs","difficulty":"medium","tags":["递归","链表"]},
  {"id":25,"title":"K 个一组翻转链表","slug":"reverse-nodes-in-k-group","difficulty":"hard","tags":["递归","链表"]},
  {"id":31,"title":"下一个排列","slug":"next-permutation","difficulty":"medium","tags":["数组","双指针"]},
  {"id":32,"title":"最长有效括号","slug":"longest-valid-parentheses","difficulty":"hard","tags":["栈","字符串","动态规划"]},
  {"id":33,"title":"搜索旋转排序数组","slug":"search-in-rotated-sorted-array","difficulty":"medium","tags":["数组","二分查找"]},
  {"id":34,"title":"在排序数组中查找元素的第一个和最后一个位置","slug":"find-first-and-last-position-of-element-in-sorted-array","difficulty":"medium","tags":["数组","二分查找"]},
  {"id":35,"title":"搜索插入位置","slug":"search-insert-position","difficulty":"easy","tags":["数组","二分查找"]},
  {"id":39,"title":"组合总和","slug":"combination-sum","difficulty":"medium","tags":["数组","回溯"]},
  {"id":41,"title":"缺失的第一个正数","slug":"first-missing-positive","difficulty":"hard","tags":["数组","哈希表"]},
  {"id":42,"title":"接雨水","slug":"trapping-rain-water","difficulty":"hard","tags":["栈","数组","双指针","动态规划"]},
  {"id":45,"title":"跳跃游戏 II","slug":"jump-game-ii","difficulty":"medium","tags":["贪心","数组","动态规划"]},
  {"id":46,"title":"全排列","slug":"permutations","difficulty":"medium","tags":["数组","回溯"]},
  {"id":48,"title":"旋转图像","slug":"rotate-image","difficulty":"medium","tags":["数组","数学","矩阵"]},
  {"id":49,"title":"字母异位词分组","slug":"group-anagrams","difficulty":"medium","tags":["数组","哈希表","字符串","排序"]},
  {"id":51,"title":"N 皇后","slug":"n-queens","difficulty":"hard","tags":["数组","回溯"]},
  {"id":53,"title":"最大子数组和","slug":"maximum-subarray","difficulty":"medium","tags":["数组","动态规划"]},
  {"id":54,"title":"螺旋矩阵","slug":"spiral-matrix","difficulty":"medium","tags":["数组","矩阵","模拟"]},
  {"id":55,"title":"跳跃游戏","slug":"jump-game","difficulty":"medium","tags":["贪心","数组","动态规划"]},
  {"id":56,"title":"合并区间","slug":"merge-intervals","difficulty":"medium","tags":["数组","排序"]},
  {"id":62,"title":"不同路径","slug":"unique-paths","difficulty":"medium","tags":["数学","动态规划","组合数学"]},
  {"id":64,"title":"最小路径和","slug":"minimum-path-sum","difficulty":"medium","tags":["数组","动态规划","矩阵"]},
  {"id":70,"title":"爬楼梯","slug":"climbing-stairs","difficulty":"easy","tags":["记忆化搜索","数学","动态规划"]},
  {"id":72,"title":"编辑距离","slug":"edit-distance","difficulty":"medium","tags":["字符串","动态规划"]},
  {"id":73,"title":"矩阵置零","slug":"set-matrix-zeroes","difficulty":"medium","tags":["数组","哈希表","矩阵"]},
  {"id":74,"title":"搜索二维矩阵","slug":"search-a-2d-matrix","difficulty":"medium","tags":["数组","二分查找","矩阵"]},
  {"id":75,"title":"颜色分类","slug":"sort-colors","difficulty":"medium","tags":["数组","双指针","排序"]},
  {"id":76,"title":"最小覆盖子串","slug":"minimum-window-substring","difficulty":"hard","tags":["哈希表","字符串","滑动窗口"]},
  {"id":78,"title":"子集","slug":"subsets","difficulty":"medium","tags":["位运算","数组","回溯"]},
  {"id":79,"title":"单词搜索","slug":"word-search","difficulty":"medium","tags":["数组","字符串","回溯","深度优先搜索","矩阵"]},
  {"id":84,"title":"柱状图中最大的矩形","slug":"largest-rectangle-in-histogram","difficulty":"hard","tags":["栈","数组","单调栈"]},
  {"id":94,"title":"二叉树的中序遍历","slug":"binary-tree-inorder-traversal","difficulty":"easy","tags":["树","二叉树","深度优先搜索"]},
  {"id":98,"title":"验证二叉搜索树","slug":"validate-binary-search-tree","difficulty":"medium","tags":["树","深度优先搜索","二叉搜索树","二叉树"]},
  {"id":101,"title":"对称二叉树","slug":"symmetric-tree","difficulty":"easy","tags":["树","深度优先搜索","广度优先搜索","二叉树"]},
  {"id":102,"title":"二叉树的层序遍历","slug":"binary-tree-level-order-traversal","difficulty":"medium","tags":["树","广度优先搜索","二叉树"]},
  {"id":104,"title":"二叉树的最大深度","slug":"maximum-depth-of-binary-tree","difficulty":"easy","tags":["树","二叉树","深度优先搜索","广度优先搜索"]},
  {"id":105,"title":"从前序与中序遍历序列构造二叉树","slug":"construct-binary-tree-from-preorder-and-inorder-traversal","difficulty":"medium","tags":["树","数组","哈希表","分治","二叉树"]},
  {"id":108,"title":"将有序数组转换为二叉搜索树","slug":"convert-sorted-array-to-binary-search-tree","difficulty":"easy","tags":["树","二叉搜索树","数组","分治","二叉树"]},
  {"id":114,"title":"二叉树展开为链表","slug":"flatten-binary-tree-to-linked-list","difficulty":"medium","tags":["栈","树","深度优先搜索","链表","二叉树"]},
  {"id":118,"title":"杨辉三角","slug":"pascals-triangle","difficulty":"easy","tags":["数组","数学","动态规划"]},
  {"id":121,"title":"买卖股票的最佳时机","slug":"best-time-to-buy-and-sell-stock","difficulty":"easy","tags":["数组","动态规划"]},
  {"id":124,"title":"二叉树中的最大路径和","slug":"binary-tree-maximum-path-sum","difficulty":"hard","tags":["树","深度优先搜索","动态规划","二叉树"]},
  {"id":128,"title":"最长连续序列","slug":"longest-consecutive-sequence","difficulty":"medium","tags":["并查集","数组","哈希表"]},
  {"id":131,"title":"分割回文串","slug":"palindrome-partitioning","difficulty":"medium","tags":["字符串","动态规划","回溯"]},
  {"id":136,"title":"只出现一次的数字","slug":"single-number","difficulty":"easy","tags":["位运算","数组"]},
  {"id":138,"title":"随机链表的复制","slug":"copy-list-with-random-pointer","difficulty":"medium","tags":["哈希表","链表"]},
  {"id":139,"title":"单词拆分","slug":"word-break","difficulty":"medium","tags":["字典树","记忆化搜索","数组","哈希表","字符串","动态规划"]},
  {"id":141,"title":"环形链表","slug":"linked-list-cycle","difficulty":"easy","tags":["链表","双指针"]},
  {"id":142,"title":"环形链表 II","slug":"linked-list-cycle-ii","difficulty":"medium","tags":["哈希表","链表","双指针"]},
  {"id":146,"title":"LRU 缓存","slug":"lru-cache","difficulty":"medium","tags":["设计","哈希表","链表","双向链表"]},
  {"id":148,"title":"排序链表","slug":"sort-list","difficulty":"medium","tags":["链表","双指针","分治","排序","归并排序"]},
  {"id":152,"title":"乘积最大子数组","slug":"maximum-product-subarray","difficulty":"medium","tags":["数组","动态规划"]},
  {"id":153,"title":"寻找旋转排序数组中的最小值","slug":"find-minimum-in-rotated-sorted-array","difficulty":"medium","tags":["数组","二分查找"]},
  {"id":155,"title":"最小栈","slug":"min-stack","difficulty":"medium","tags":["栈","设计"]},
  {"id":160,"title":"相交链表","slug":"intersection-of-two-linked-lists","difficulty":"easy","tags":["哈希表","链表","双指针"]},
  {"id":169,"title":"多数元素","slug":"majority-element","difficulty":"easy","tags":["数组","哈希表","分治","计数","排序"]},
  {"id":189,"title":"轮转数组","slug":"rotate-array","difficulty":"medium","tags":["数组","数学","双指针"]},
  {"id":198,"title":"打家劫舍","slug":"house-robber","difficulty":"medium","tags":["数组","动态规划"]},
  {"id":199,"title":"二叉树的右视图","slug":"binary-tree-right-side-view","difficulty":"medium","tags":["树","深度优先搜索","广度优先搜索","二叉树"]},
  {"id":200,"title":"岛屿数量","slug":"number-of-islands","difficulty":"medium","tags":["深度优先搜索","广度优先搜索","并查集"]},
  {"id":206,"title":"反转链表","slug":"reverse-linked-list","difficulty":"easy","tags":["链表","递归"]},
  {"id":207,"title":"课程表","slug":"course-schedule","difficulty":"medium","tags":["深度优先搜索","广度优先搜索","图","拓扑排序"]},
  {"id":208,"title":"实现 Trie（前缀树）","slug":"implement-trie-prefix-tree","difficulty":"medium","tags":["设计","字典树","哈希表","字符串"]},
  {"id":215,"title":"数组中的第 K 个最大元素","slug":"kth-largest-element-in-an-array","difficulty":"medium","tags":["数组","分治","快速选择","排序","堆（优先队列）"]},
  {"id":226,"title":"翻转二叉树","slug":"invert-binary-tree","difficulty":"easy","tags":["树","二叉树","深度优先搜索"]},
  {"id":230,"title":"二叉搜索树中第 K 小的元素","slug":"kth-smallest-element-in-a-bst","difficulty":"medium","tags":["树","深度优先搜索","二叉搜索树","二叉树"]},
  {"id":234,"title":"回文链表","slug":"palindrome-linked-list","difficulty":"easy","tags":["栈","递归","链表","双指针"]},
  {"id":236,"title":"二叉树的最近公共祖先","slug":"lowest-common-ancestor-of-a-binary-tree","difficulty":"medium","tags":["树","深度优先搜索","二叉树"]},
  {"id":238,"title":"除自身以外数组的乘积","slug":"product-of-array-except-self","difficulty":"medium","tags":["数组","前缀和"]},
  {"id":239,"title":"滑动窗口最大值","slug":"sliding-window-maximum","difficulty":"hard","tags":["队列","数组","滑动窗口","单调队列"]},
  {"id":240,"title":"搜索二维矩阵 II","slug":"search-a-2d-matrix-ii","difficulty":"medium","tags":["数组","二分查找","分治","矩阵"]},
  {"id":279,"title":"完全平方数","slug":"perfect-squares","difficulty":"medium","tags":["广度优先搜索","数学","动态规划"]},
  {"id":283,"title":"移动零","slug":"move-zeroes","difficulty":"easy","tags":["数组","双指针"]},
  {"id":287,"title":"寻找重复数","slug":"find-the-duplicate-number","difficulty":"medium","tags":["位运算","数组","双指针","二分查找"]},
  {"id":295,"title":"数据流的中位数","slug":"find-median-from-data-stream","difficulty":"hard","tags":["设计","双指针","数据流","排序","堆（优先队列）"]},
  {"id":300,"title":"最长递增子序列","slug":"longest-increasing-subsequence","difficulty":"medium","tags":["数组","二分查找","动态规划"]},
  {"id":322,"title":"零钱兑换","slug":"coin-change","difficulty":"medium","tags":["广度优先搜索","数组","动态规划"]},
  {"id":347,"title":"前 K 个高频元素","slug":"top-k-frequent-elements","difficulty":"medium","tags":["数组","哈希表","分治","桶排序","计数","堆（优先队列）"]},
  {"id":394,"title":"字符串解码","slug":"decode-string","difficulty":"medium","tags":["栈","递归","字符串"]},
  {"id":416,"title":"分割等和子集","slug":"partition-equal-subset-sum","difficulty":"medium","tags":["数组","动态规划"]},
  {"id":437,"title":"路径总和 III","slug":"path-sum-iii","difficulty":"medium","tags":["树","深度优先搜索","二叉树","前缀和"]},
  {"id":438,"title":"找到字符串中所有字母异位词","slug":"find-all-anagrams-in-a-string","difficulty":"medium","tags":["哈希表","字符串","滑动窗口"]},
  {"id":543,"title":"二叉树的直径","slug":"diameter-of-binary-tree","difficulty":"easy","tags":["树","深度优先搜索","二叉树"]},
  {"id":560,"title":"和为 K 的子数组","slug":"subarray-sum-equals-k","difficulty":"medium","tags":["数组","哈希表","前缀和"]},
  {"id":739,"title":"每日温度","slug":"daily-temperatures","difficulty":"medium","tags":["栈","数组","单调栈"]},
  {"id":763,"title":"划分字母区间","slug":"partition-labels","difficulty":"medium","tags":["贪心","哈希表","双指针","字符串"]},
  {"id":994,"title":"腐烂的橘子","slug":"rotting-oranges","difficulty":"medium","tags":["广度优先搜索","数组","矩阵"]},
  {"id":1143,"title":"最长公共子序列","slug":"longest-common-subsequence","difficulty":"medium","tags":["字符串","动态规划"]},
];

export const allTags = ["二分查找","二叉搜索树","二叉树","位运算","分治","前缀和","动态规划","单调栈","单调队列","双向链表","双指针","哈希表","回溯","图","堆（优先队列）","字典树","字符串","并查集","广度优先搜索","归并排序","快速选择","拓扑排序","排序","数学","数据流","数组","栈","树","桶排序","模拟","深度优先搜索","滑动窗口","矩阵","组合数学","计数","记忆化搜索","设计","贪心","递归","链表","队列"];

const problemLoaders = new Map([
  [1, () => import('./p001-two-sum.js')],
  [2, () => import('./p002-add-two-numbers.js')],
  [3, () => import('./p003-longest-substring-without-repeating-characters.js')],
  [4, () => import('./p004-median-of-two-sorted-arrays.js')],
  [5, () => import('./p005-longest-palindromic-substring.js')],
  [11, () => import('./p011-container-with-most-water.js')],
  [15, () => import('./p015-3sum.js')],
  [17, () => import('./p017-letter-combinations-of-a-phone-number.js')],
  [19, () => import('./p019-remove-nth-node-from-end-of-list.js')],
  [20, () => import('./p020-valid-parentheses.js')],
  [21, () => import('./p021-merge-two-sorted-lists.js')],
  [22, () => import('./p022-generate-parentheses.js')],
  [23, () => import('./p023-merge-k-sorted-lists.js')],
  [24, () => import('./p024-swap-nodes-in-pairs.js')],
  [25, () => import('./p025-reverse-nodes-in-k-group.js')],
  [31, () => import('./p031-next-permutation.js')],
  [32, () => import('./p032-longest-valid-parentheses.js')],
  [33, () => import('./p033-search-in-rotated-sorted-array.js')],
  [34, () => import('./p034-find-first-and-last-position-of-element-in-sorted-array.js')],
  [35, () => import('./p035-search-insert-position.js')],
  [39, () => import('./p039-combination-sum.js')],
  [41, () => import('./p041-first-missing-positive.js')],
  [42, () => import('./p042-trapping-rain-water.js')],
  [45, () => import('./p045-jump-game-ii.js')],
  [46, () => import('./p046-permutations.js')],
  [48, () => import('./p048-rotate-image.js')],
  [49, () => import('./p049-group-anagrams.js')],
  [51, () => import('./p051-n-queens.js')],
  [53, () => import('./p053-maximum-subarray.js')],
  [54, () => import('./p054-spiral-matrix.js')],
  [55, () => import('./p055-jump-game.js')],
  [56, () => import('./p056-merge-intervals.js')],
  [62, () => import('./p062-unique-paths.js')],
  [64, () => import('./p064-minimum-path-sum.js')],
  [70, () => import('./p070-climbing-stairs.js')],
  [72, () => import('./p072-edit-distance.js')],
  [73, () => import('./p073-set-matrix-zeroes.js')],
  [74, () => import('./p074-search-a-2d-matrix.js')],
  [75, () => import('./p075-sort-colors.js')],
  [76, () => import('./p076-minimum-window-substring.js')],
  [78, () => import('./p078-subsets.js')],
  [79, () => import('./p079-word-search.js')],
  [84, () => import('./p084-largest-rectangle-in-histogram.js')],
  [94, () => import('./p094-binary-tree-inorder-traversal.js')],
  [98, () => import('./p098-validate-binary-search-tree.js')],
  [101, () => import('./p101-symmetric-tree.js')],
  [102, () => import('./p102-binary-tree-level-order-traversal.js')],
  [104, () => import('./p104-maximum-depth-of-binary-tree.js')],
  [105, () => import('./p105-construct-binary-tree-from-preorder-and-inorder-traversal.js')],
  [108, () => import('./p108-convert-sorted-array-to-binary-search-tree.js')],
  [114, () => import('./p114-flatten-binary-tree-to-linked-list.js')],
  [118, () => import('./p118-pascals-triangle.js')],
  [121, () => import('./p121-best-time-to-buy-and-sell-stock.js')],
  [124, () => import('./p124-binary-tree-maximum-path-sum.js')],
  [128, () => import('./p128-longest-consecutive-sequence.js')],
  [131, () => import('./p131-palindrome-partitioning.js')],
  [136, () => import('./p136-single-number.js')],
  [138, () => import('./p138-copy-list-with-random-pointer.js')],
  [139, () => import('./p139-word-break.js')],
  [141, () => import('./p141-linked-list-cycle.js')],
  [142, () => import('./p142-linked-list-cycle-ii.js')],
  [146, () => import('./p146-lru-cache.js')],
  [148, () => import('./p148-sort-list.js')],
  [152, () => import('./p152-maximum-product-subarray.js')],
  [153, () => import('./p153-find-minimum-in-rotated-sorted-array.js')],
  [155, () => import('./p155-min-stack.js')],
  [160, () => import('./p160-intersection-of-two-linked-lists.js')],
  [169, () => import('./p169-majority-element.js')],
  [189, () => import('./p189-rotate-array.js')],
  [198, () => import('./p198-house-robber.js')],
  [199, () => import('./p199-binary-tree-right-side-view.js')],
  [200, () => import('./p200-number-of-islands.js')],
  [206, () => import('./p206-reverse-linked-list.js')],
  [207, () => import('./p207-course-schedule.js')],
  [208, () => import('./p208-implement-trie-prefix-tree.js')],
  [215, () => import('./p215-kth-largest-element-in-an-array.js')],
  [226, () => import('./p226-invert-binary-tree.js')],
  [230, () => import('./p230-kth-smallest-element-in-a-bst.js')],
  [234, () => import('./p234-palindrome-linked-list.js')],
  [236, () => import('./p236-lowest-common-ancestor-of-a-binary-tree.js')],
  [238, () => import('./p238-product-of-array-except-self.js')],
  [239, () => import('./p239-sliding-window-maximum.js')],
  [240, () => import('./p240-search-a-2d-matrix-ii.js')],
  [279, () => import('./p279-perfect-squares.js')],
  [283, () => import('./p283-move-zeroes.js')],
  [287, () => import('./p287-find-the-duplicate-number.js')],
  [295, () => import('./p295-find-median-from-data-stream.js')],
  [300, () => import('./p300-longest-increasing-subsequence.js')],
  [322, () => import('./p322-coin-change.js')],
  [347, () => import('./p347-top-k-frequent-elements.js')],
  [394, () => import('./p394-decode-string.js')],
  [416, () => import('./p416-partition-equal-subset-sum.js')],
  [437, () => import('./p437-path-sum-iii.js')],
  [438, () => import('./p438-find-all-anagrams-in-a-string.js')],
  [543, () => import('./p543-diameter-of-binary-tree.js')],
  [560, () => import('./p560-subarray-sum-equals-k.js')],
  [739, () => import('./p739-daily-temperatures.js')],
  [763, () => import('./p763-partition-labels.js')],
  [994, () => import('./p994-rotting-oranges.js')],
  [1143, () => import('./p1143-longest-common-subsequence.js')],
]);

export async function loadProblem(id) {
  const numericId = Number(id);
  const loader = problemLoaders.get(numericId);
  if (!loader) throw new Error(`题目不存在: ${id}`);
  return (await loader()).default;
}
